### ISSUE TITLE
feature: Fix HTML strings pasted in templ context

### ISSUE THREAD

**Issue by peteraba** [templ-go/templ-jetbrains#12]
It'd be great if the extension could replace `<br>` tags with `<br />` when pasting in text. Sometimes I paste in HTML containing SVGs and what not, so it becomes harder to spot broken tags.

**Comment by joerdav** [comment]
Good point, I'll close this in favour of tracking this in https://github.com/a-h/templ/issues/637

**Comment by peteraba** [comment]
@bastianwegge Obviously, if the changes proposed in https://github.com/a-h/templ/issues/637 were to be implemented, this suggestion would make little sense.

@joerdav you're marking this as complete, but is it?

**Comment by joerdav** [comment]
Sorry, I tend to just use the close button, then comment with my reasoning, I've updated the status.

**Comment by peteraba** [comment]
@joerdav fair enough. thank you so much for the effort and the plugin itself! :pray:

**Comment by a-h** [comment]
@peteraba - there's a fix up for good elements in the main branch of templ now. `templ fmt` now will auto update `<br>` to `<br/>`. If you had time to test it with your SVG use case, that would be appreciated.

Alternatively, drop a code sample, and I'll make sure it isn't damaged by the update.
