### ISSUE TITLE
Incompatible version

### ISSUE THREAD

**Issue by koalazub** [templ-go/templ-jetbrains#13]
Plugin not usable in EAP. Which, fair enough if you're waiting for the release first. 

Using GoLand version `Build #GO-241.8102.131` EAP

<img width="303" alt="image" src="https://github.com/templ-go/templ-jetbrains/assets/7111524/753c4008-456a-4f46-84f0-cdf8d6440dad">

**Comment by jvgrootveld** [comment]
I just noticed this to. The compatibility range on the the [plugin page](https://plugins.jetbrains.com/plugin/23088-templ/versions) is showing that that the supported version is going down?

![image](https://github.com/templ-go/templ-jetbrains/assets/1201849/c0125303-92c4-4c82-ba7f-9aba12ab7f94)

**Comment by joerdav** [comment]
Latest version should have support. Please reopen if the issue persists!

**Comment by jvgrootveld** [comment]
Confirmed with `2023.3.3`
![image](https://github.com/templ-go/templ-jetbrains/assets/1201849/c077c9e0-0a94-465e-ba75-309ef67845ba)

**Comment by koalazub** [comment]
Epic. Thanks so much!
