### ISSUE TITLE
CSS snippets and code completion support

### ISSUE THREAD

**Issue by abolfazlakbarzadeh** [templ-go/templ-jetbrains#36]
Hi, Does templ plugin support css snippets and code completion? I just made a css scope in .templ file and tried to add some css code but it doesn't highlight codes
```
css navItem() {
    display: flex;
    align-items: center;
    gap: 2rem;
    border-bottom: 1px solid transparent;
}
```

**Comment by joerdav** [comment]
Currently no, our main focus at the moment is improving the go-in-templ experience, but we do want to improve the css-in-templ and js-in-templ experience, specially in style tags and script tags.
