### ISSUE TITLE
go command required, not found: exec: "go": executable file not found in $PATH: stderr

### ISSUE THREAD

**Issue by yazalulloa** [templ-go/templ-jetbrains#37]
I'm getting this errors when opening a .templ file

templ: Error loading workspace folders (expected 1, got 0) failed to load view for file:///home/yaz/workspace/personal/golang/condo-manager-golang/src/view: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:

templ: Error loading packages: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:

![image](https://github.com/user-attachments/assets/ad865842-3fab-4329-abf2-0cd50a0d0e70)

OS: Ubuntu 22.04.4
Go: go1.22.5 linux/amd64
Intellij: IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Templ: v0.2.747
Plugin: 0.0.14

**Comment by joerdav** [comment]
Hi, thanks for the error report. Can you please send the result of the command `templ info`?

**Comment by schmiddim** [comment]
Hi @joerdav  Same Problem here 

> templ: Error loading workspace folders (expected 1, got 0) failed to load view for file:///home/ms/code/kozukai/web/views/accomplishments: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:



> templ: Error loading packages: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:

```
templ  version
v0.2.747
```
```
templ info 
usage: templ <command> [<args>...]

templ - build HTML UIs with Go

See docs at https://templ.guide

commands:
  generate   Generates Go code from templ files
  fmt        Formats templ files
  lsp        Starts a language server for templ files
  version    Prints the version
```

```lang=bash
echo $PATH |grep go
/home/ms/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/bin:/home/ms/go/bin:/home/ms/.krew/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/ms/.rd/bin:/home/ms/miniconda3/bin:/home/ms/.krew/bin:/home/ms/go/bin/bin:/home/ms/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/bin:/home/ms/.rd/bin:/home/ms/.local/bin:/home/ms/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ms/.local/share/JetBrains/Toolbox/scripts:/home/ms/.local/bin:/usr/local/go/bin:/home/ms/bin:/home/ms/.kerl/25.2.3/bin/:/home/ms/.kerl/elixir-otp-25/bin:/home/ms/.rd/bin:/home/ms/.local/bin/go

```

**Comment by joerdav** [comment]
@schmiddim sorry, the `templ info` command is quite new, could you update your templ version please and try again?

**Comment by schmiddim** [comment]
/home/ms/.local/bin/go/templ  info
(✓) os [ goos=linux goarch=amd64 ]
(✓) go [ location=/usr/local/go/bin/go version=go version go1.21.1 linux/amd64 ]
(✓) gopls [ location=/home/ms/.local/bin/go/gopls version=golang.org/x/tools/gopls v0.16.1 ]
(✓) templ [ location=/home/ms/.local/bin/go/templ version=v0.2.771 ]

**Comment by yazalulloa** [comment]
Hi, sorry for the late answer, I updated to v0.2.778 but the error persists

This is the output of templ info:

(✓) os [ goos=linux goarch=amd64 ]
(✓) go [ location=/usr/local/go/bin/go version=go version go1.23.1 linux/amd64 ]
(✓) gopls [ location=/home/yaz/go/bin/gopls version=golang.org/x/tools/gopls v0.16.1 ]
(✓) templ [ location=/home/yaz/go/bin/templ version=v0.2.778 ]

**Comment by DemonTPx** [comment]
I fixed this problem by adding a file `~/.config/environment.d/go.conf` containing:

```
GOROOT="$HOME/go/go1.23.0"
GOPATH="$HOME/go:$GOROOT"
GOBIN="$GOROOT/bin"
PATH="$GOBIN:$PATH"
```

After this, log out and in again (or reboot)!

The `GOROOT` must point to the Go SDK on your disk (in my case `$HOME/go/go1.23.0`, in your case probably `$HOME/go`.

What this does is add the go bin path to the global `$PATH` for your user. These files are only applied when logging in your desktop environment and the `$PATH` will be passed to GoLand or IntelliJ when you launch them.

If you only add the go bin path to your `.bashrc`, `.zshrc` or `.profile` or whatever is not enough, because they are only executed once you start a new terminal/shell.

**Comment by joerdav** [comment]
This should now be closed by https://github.com/templ-go/templ-jetbrains/pull/39
