### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Laubi** [templ-go/templ-jetbrains#38]
Currently, the project is under no license, meaning `no one may reproduce, distribute, or create derivative works from your work.`

To quote GitHub directly:
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. [...] [1]

This has the obvious implication that the project can't legally be used anywhere without explicit permission. 

The Plugin on IntelliJ defines the plugin as 'MIT', but it has to be with the source code as well [2].

[1] https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
[2] https://plugins.jetbrains.com/plugin/23088-templ

**Comment by joerdav** [comment]
Thanks, fixed that!
